version: '3.5'
services:
 grafana:
  image: grafana/grafana:latest
  restart: always
  ports:
   - "3000:3000"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - ./db/:/db:rw
   - ./env_gra/grafana.ini:/etc/grafana/grafana.ini
   - /var/log/grafana:/var/log/grafana
  environment:
   - GF_SECURITY_ADMIN_PASSWORD=xxx@123
   - GF_INSTALL_IMAGE_RENDERER_PLUGIN=true
   - GRAFANA_VERSION=latest
  networks:
   gra_net:

 renderer:
  image: grafana/grafana-image-renderer:latest
  restart: always
  ports:
   - "3001:8081"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
  environment:
   - GF_RENDERER_PLUGIN_TZ=Asia/Shanghai
   - GF_RENDERER_PLUGIN_IGNORE_HTTPS_ERRORS=true
  networks:
   gra_net:

networks:
  gra_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.240.0/24